name: promodoro
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  date_time: ^0.11.0
  flutter:
    sdk: flutter
  hive: ^2.2.3    # Core Hive package
  hive_flutter: ^1.1.0
  uuid: ^4.5.1
  bloc: ^9.0.0
  flutter_bloc:
  shared_preferences: ^2.5.3
  fl_chart: ^0.70.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^1.1.0  # For generating adapters
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logos/
  
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
  

